### ISSUE TITLE
Can't select iPad Pro devices by name

### ISSUE THREAD

**Issue by kwood** [facebook/idb#392]
Currently it doesn't seem possible to select iPad Pro devices, because by default their names include characters that the arguments parser doesn't allow.

`fbsimctl list`:
```
D7E52ED8-D64E-424B-9A38-06F7739901D7 | iPad Pro (12.9 inch) | Shutdown | iPad Pro (12.9-inch) | iOS 10.2
...
98DF5058-DC91-47DD-951B-9158D091CEBA | iPhone 7 | Booted | iPhone 7 | iOS 10.2
```

It's possible to select the iPhone 7 by name:

`fbsimctl 'iPhone 7' list`

```
98DF5058-DC91-47DD-951B-9158D091CEBA | iPhone 7 | Booted | iPhone 7 | iOS 10.2
```

...but you can't select the iPad Pro:
`fbsimctl 'iPad Pro (12.9 inch)' list`
```
Failed to Parse Command '["iPad Pro (12.9 inch)", "list"]' does not match '[fbsimctl {{ [output] | [management] | --set <directory> }}* [targets]? [target-format]* {{ [action] ... -- [action] }}+
```

**Comment by lawrencelomax** [comment]
So it looks like the `SimDeviceType` canonical representation has a dash in it: `iPad Pro (12.9-inch)` vs. the default name for one of these Device Types `iPad Pro (12.9 inch)`.

`fbsimctl 'iPad Pro (12.9-inch)' list` should work for the time being. However we will need to do some re-working of the Configuration classes so that there can be a many-to-one mapping of `FBDeviceModel` to the `SimDeviceType` canonical representation.

**Comment by kwood** [comment]
Yep -- that works
