### ISSUE TITLE
It takes to long to launch the application between each test case.

### ISSUE THREAD

**Issue by amesandy** [facebook/idb#408]
we have one scheme with several .swift files in which we also have multiple test cases.
The 2 simulators open fine and application launches , the problem is between each test cases the app closes and reopen (due to super.setup() and teardown() methods on UITesting) and it takes around 37 seconds to relaunch the app, I compared it with 'Fastlane scan' which takes only 6 seconds to relaunch the app to start with the next test case.

Any ideas why this can take  too long.?

**Comment by lawrencelomax** [comment]
Is this the base `XCTestCase` of that is causing the Application to relaunch and hence the slowdown? Do you have any additional logs from the output of the process that is launching the UITest? This can help debug what is being slow and if there are any stalls that could be slowing down test execution.

I would assume that fastlane is calling `xcodebuild`. The launching of a UITest target does more than just relaunch the Application, since a connection to `testmanagerd` also has to be established.

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
