### ISSUE TITLE
FBsimctl issue on detox installation.

### ISSUE THREAD

**Issue by harishbarge** [facebook/idb#416]
using target fbsimctl
using command build
using output directory /usr/local/Cellar/fbsimctl/HEAD-85b4660
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20170529-14527-1lol0ig/fbsimctl /private/tmp/fbsimctl-20170529-14527-1lol0ig
dyld: Symbol not found: __TMV6Result8AnyError
Referenced from: /usr/local/Cellar/carthage/0.23.0/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
in /usr/local/Cellar/carthage/0.23.0/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
./build.sh: line 38: 14862 Abort trap: 6 carthage bootstrap --platform Mac

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
