### ISSUE TITLE
Simulator closes suddenly sometimes

### ISSUE THREAD

**Issue by silyevsk** [facebook/idb#423]
After booting a simulator with fbsimctl, it sometimes crashes suddenly. Unfortunately, it's not always reproducible, but we have this happening quite often on several machines. It looks like it happens much more often with the more recent fbsimctl (but not for sure).

To reproduce:
- Close the simulator
- Run `fbsimctl <device_id> boot`
Rarely it will crash during the boot, but most often it will crash when it receives focus. Usually I can reproduce it by activating any other app and then clicking back on the simulator (have to do it several times usually).

My configuration is:
- macOS Sierra 10.12.3
- Xcode 8.3.2

I've tried to run the simulator with the same args and env. vars like fbsimctl does, and the issue didn't reproduce. fbsimctl launches simulator with stdout/stderr pipes, so may be it's somehow related (I couldn't check this yet, because somehow the issue became not reproducible on my machine for now..)

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
