### ISSUE TITLE
Patch version is not returned for simulator

### ISSUE THREAD

**Issue by NickAb** [facebook/idb#428]
Running `fbsimctl --json list` returns full `os` version for real devices, but only first two components for simulators.

Sample output:
```
{"event_type":"discrete","timestamp":1499765200,"subject":{"arch":"arm64","state":"Unknown","model":"iPhone 6 Plus","name":"NAME","os":"iOS 10.2.1","udid":"c865..."},"event_name":"list"}
{"event_type":"discrete","timestamp":1499765200,"subject":{"arch":"x86_64","state":"Shutdown","model":"iPhone 6","name":"NAME","os":"iOS 10.3","udid":"584514A8..."},"event_name":"list"}
```
How can we get full os version (including patch segment) for simulators?

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. idb fixed that issue and returns all the details for both simulators and devices. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
