### ISSUE TITLE
How Can I get iOS Device ip address?

### ISSUE THREAD

**Issue by tianyig** [facebook/idb#478]
I want to get conneted device IP address,Is anyway use fbsimctl to get it?

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen

**Comment by lawrencelomax** [comment]
There may be ways of getting device configuration using `MobileDevice` but I'm not aware of them. If you find out we can add this into `idb describe`
