### ISSUE TITLE
No such path "CoreSimulator.framework"

### ISSUE THREAD

**Issue by evandrix** [facebook/idb#482]
`$ brew tap facebook/fb && brew install fbsimctl`
> ...fbsimctl 0.4.0 is already installed...

`$ fbsimctl list`
> Error Domain=com.facebook.FBControlCore Code=0 "Attempting to load a file at path '/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist" UserInfo={NSLocalizedDescription=Attempting to load a file at path '/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist}

I only have `SimulatorKit.framework` under `Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/`; there is no `CoreSimulator.framework`

I'm on OSX v10.12.6, running XCode v9.2 (9C40b).

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
