### ISSUE TITLE
Unable to boot simulator: operation timed out

### ISSUE THREAD

**Issue by beefon** [facebook/idb#484]
On one of the systems I constantly get this error when I invoke `fbsimctl --set /Users/user/sims/ "810C66F6-4F20-4AE2-8350-8DD2BFC44779" boot --direct-launch`. 
It waits for some time (maybe 30 seconds) and then it fails with an error: `launchd failed to respond`, the launchd config plist is present and it is similar to the plist which I took from the system where fbsimctl is able to boot the simulator. The log in the `/tmp/com.apple.CoreSImulator...` folder has only single line: `launchd missing or invalid configuration plist`.

**Comment by beefon** [comment]
Is there any way I can debug this to understand what's broken with my setup?

**Comment by beefon** [comment]
I've created another system user and fbsimctl works great over here, so it must be something related to the user configuration, but I don't understand where to look at. It would be very helpful to get some pointers so I can clean things up.

**Comment by lawrencelomax** [comment]
We actually added better tracking of booting by hooking into some `CoreSimulator` callbacks that aren't exposed in `simctl`. You might see better logging.

If `launchd` is failing to respond, this suggests that things are super swamped though, and `CoreSimulatorService` may be in a bad place, which is why a different user may have worked for you. Killing `CoreSimulatorService` may also help in these circumstances.

**Comment by Sameer-Ijaz** [comment]
I was able to solve the issue by doing this https://www.youtube.com/watch?v=9bDDWNoibIk&t=12s&ab_channel=SgtSam
