### ISSUE TITLE
Cannot start and communicate with Instruments Remote Server on iOS 14

### ISSUE THREAD

**Issue by davidrogers-unity** [facebook/idb#630]
### Description

The service ```com.apple.instruments.remoteserver``` was removed in iOS 14 in favor of what I think is a fully secured service ```com.apple.instruments.remoteserver.DVTSecureSocketProxy```.

As a result any commands in idb that rely on the instruments server do not work on devices.

### Reproduction

Attempt to launch and application using idb on a device with iOS 14 installed.

**Comment by lawrencelomax** [comment]
I hope that this is just a change in service name instead of a changing of the underlying protocol. Will take a quick look.

**Comment by lawrencelomax** [comment]
Just changing the server over does not work by itself. My guess is whatever this new protocol is, is at the protocol layer so just having a secure transport (as we currently do) is insufficient. 

I can't claim to be a massive expert here, since a lot of the exploration and documentation here is based on the work of @troybowman  in https://github.com/troybowman/ios_instruments_client .

**Comment by lawrencelomax** [comment]
The relevant code is in `/Applications/xcode_12_gm.app/Contents/Applications/Instruments.app/Contents/PlugIns/XRMobileDeviceDiscoveryPlugIn.xrplugin/Contents/MacOS/XRMobileDeviceDiscoveryPlugIn`. It selects the appropriate service between `com.apple.instruments.remoteserver` and `com.apple.instruments.remoteserver.DVTSecureSocketProxy` (likely depending on the Xcode/iOS Version)

This is where the appropriate service channel is created:

<img width="1669" alt="Screen Shot 2020-10-15 at 1 54 26 PM" src="https://user-images.githubusercontent.com/217883/96129123-24f56780-0eee-11eb-93a1-ea553e0235e5.png">

Then there's `DVTSecureSocketProxy_Create`, which I assume wraps the transport in some way

<img width="484" alt="Screen Shot 2020-10-15 at 1 54 31 PM" src="https://user-images.githubusercontent.com/217883/96129196-3dfe1880-0eee-11eb-969e-dfdd0e98fffa.png">

**Comment by lawrencelomax** [comment]
Panic over, I've got this working on iOS 14 by using the secure AM commands. Will hopefully get something landed soon

**Comment by davidrogers-unity** [comment]
Wow that was quick! I was just thinking about how we could figure this out together while dropping off my daughter at daycare and saw this when I came back. Awesome work! Don't hesitate to let me know if you need any other help with it. And thanks again!

I may open a PR at some point to add incremental deploys as well. I've had that working well for a couple weeks now.

**Comment by lawrencelomax** [comment]
> Wow that was quick!

This has happened before in [previous iOS Versions so it was just a case of changing a few things](https://github.com/facebook/idb/commit/ccff041579475e184695b2cefdc952211dbd6342#diff-7147fc58258b69f4ceb58490a56c16ef795741731f0aed05516b44d397d1e4af). The details are `FBAMDServiceConnection`, basically we can send bytes over the wire using either raw socket access, or using the `AMDServiceConnectionSend` `AMDServiceConnectionReceive`.

If you use the `AMD` calls then it will go through the encryption process just like a TLS'd connection. Fortunately, I've beefed up some of the API's for this since last time so it was even easier to switch it over for this service.

Just keep an eye on master, it's going through internal CI now so should be pushed very soon.
